# Generated by Django 4.1.4 on 2023-03-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_scan_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scan',
        ),
    ]
